spring:
  profiles:
    include: druid
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 8     # 连接池最大连接数，默认8
        max-wait: -1      # 连接池最大阻塞等待时间，使用负值表示没有限制， 默认-1
        max-idle: 8        # 连接池中的最大空闲连接，默认8
        min-idle: 0         # 连接池中的最小空闲连接，默认0

logging:
  level:
    com.iefihz.cloud: debug

# 另外指定rsa公私钥文件位置，可以不指定使用默认值
jwt:
  rsaPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgAVJlcg2XRI7oPdpQSiPm3NxcYWmF7XxUgkxY30HYRryIAcPn6tJ2unxD3Dor3wPQ2EMLydDxweuvFCGec36glOFRLUaN7D0FDP1gyuoOQuMdg/3EeVfXWy2ZYPTDE36zWeNVii+xCrkwYP9xZZg3zWDX7jPrTvSEKPhPdhNPtUFxTITfpo1fV5pmJU+qWJ9Ze8y+eoJ/jDFjesq1TM8pjX2ZOj7wJgz1txflx5GGMD5QAW9JUCZEGOVIFXRwURb4RBJCX8UujYjGdcWMf9oZARiS32M8OrYmwcLZfmGEISS6OtD5CPkwSg7PIFC86ZmTVVDSQMsnW/VCOvjtTQp+QIDAQAB
  rsaPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCABUmVyDZdEjug92lBKI+bc3FxhaYXtfFSCTFjfQdhGvIgBw+fq0na6fEPcOivfA9DYQwvJ0PHB668UIZ5zfqCU4VEtRo3sPQUM/WDK6g5C4x2D/cR5V9dbLZlg9MMTfrNZ41WKL7EKuTBg/3FlmDfNYNfuM+tO9IQo+E92E0+1QXFMhN+mjV9XmmYlT6pYn1l7zL56gn+MMWN6yrVMzymNfZk6PvAmDPW3F+XHkYYwPlABb0lQJkQY5UgVdHBRFvhEEkJfxS6NiMZ1xYx/2hkBGJLfYzw6tibBwtl+YYQhJLo60PkI+TBKDs8gULzpmZNVUNJAyydb9UI6+O1NCn5AgMBAAECggEAHYiavDovCHOfW/gXyRdhYdxVDHpnocqwfFtwkGIUpLtBpk/as9whMqaLnSNQGsPFBadK10n4od7M2da93zW8l/pKoVoiTTy+YjbGaddVfKuEYOw39GH1CSl+PpcVxh3rQR2lhn3p3HmEwnv/vGh/up6uyxNona9SO9KCsPDIiTjqCgOb9/357TO/Jy0/zeYTaZR5LRPYKKEJY3XiyzpAgnzykg5oC+Qi7CIri+AokTmx3cRwFlqPcycaILeuDrCba8repc5WZZ6PnCDYs0gn4/XNM/dSAQqscWB2d6jO1GHJZM87zeSiJ9SrsvplODg2RaxsJ85lMFSlGyYAV7KTnQKBgQC5PSlVJNxttRA9DyXNzcASaiy5Znrv/eL9vShMlbb8rq2y1Pf3CAKdezWxX81qqEk4b9Uyw9L+Nj2vUZ0RHsB+78KD+RODnqd04otQaunWcHOGXGWRrGC6YQeTYxVaoFdWXzGGIDdkdVGadlm+f0dVTehpPJhEZ3sd4gRruhuCEwKBgQCw7Kbs/SxVP8S+v7as7m5uLCvQqqGFpiLFqBodvglvpxzlHRb+9YD3hzMSa75M4SXmlNqCgrTGWy4Wk2CJ7+bL/I8SApqIoBIN/ZU2BRweuZPrzbG6RnmrJ05knye4rz09x+hLeEvuVOZvEQ+5X+jne0pYtydqNHf8BO+jgIZFQwKBgHU6aqTyrflT5BHwOylyc4Jz5Rfz7gthbjzMb+t/uA1TcqPBOagBTr5hEgrNqU89bxEjXRZCbY3pv8Hq8W67OnFaxIwGnj3msu06zZW4A4JtKf83DCRTpedtroCs7P+sh3kmx02tp8CQqnMJQSRYokkvA81NxsNLhdPUjJ2sauo3AoGAJjqsgw7dknoZ+CGSxmEqyXGP8iG8jxVr9AuzwPN8NH0GmFclzeece1/iYDuZviD0QJOvd33os+el2Mj1ljiZRUCIZZrca2MzI4TExgxqnBT7antiyN5LkfkHTmS5f4WWFRBqGEyhE5mSxTMJk8Ounr4cPXkt8hvuRS2H3mt6F+MCgYEAruR59MMVi0FnSntimvMkKqyKeqJm8Avq8rkh9c15m58ucJPEdj4FZnhYnK2K05zdZgr4l7As3yaBZtbEqTnY4/DdXtMUAqjW5LsbqRGsnwOQEyBr1gPMSSJOXpap0mpne6cDP+aoo1ijLdF2Jh6hjmoC/2fqv65IXW7EUyuzWto=

management:
  endpoints:
    web:
      exposure:
        include: '*'